version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "hotel"
      POSTGRES_USER: "gunhs"
      POSTGRES_PASSWORD: "kopo6ok"
    ports:
      - "5432:5432"