version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "hotel"
      POSTGRES_USER: "gunhs"
      POSTGRES_PASSWORD: "12345"
    volumes:
      - ./init-db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5433:5432"